#---------------- 服务端口-----------------------------
server:
  port: 80                                #定义服务端口
#----------------------------------------------------
#---------------redis配置----多个连接--------------------

myredis:
  redis-one:
    host: 192.168.117.148             #连接地址
    port: 6379                        #连接端口号
    password: mldnjava                #连接密码
    timeout: 1000                     #连接时间
    database: 0                       #当前对应的数据
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
      
  redis-two:  #名字随便写，没有自动配置作用，只能够读取
    host: 192.168.117.148             #连接地址
    port: 6379                        #连接端口号
    password: mldnjava                #连接密码
    timeout: 1000                     #连接时间
    database: 1                       #当前对应的数据
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
      max-wait: 100
#-----------------------------------------------------

