#---------------- 服务端口-----------------------------
server:
  port: 80                                #定义服务端口
#----------------------------------------------------

#---------------- kafka配置----------------------------
spring:
  kafka:
    bootstrap-servers:
    - kafka-single:9095                   #主机地址与端口
    template:
      default-topic: mldn-microboot       #主题
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_PLAINTEXT
#--------------------------------------------------------

