#---------------- 服务端口-----------------------------
server:
  port: 80                                #定义服务端口
#----------------------------------------------------
#---------------- rabitmq配置----------------------------
spring:
  rabbitmq:
    addresses: rabbitmq                   #RabbitMQ主机名称
    username:  mldn                       #用户名
    password:  java                       #密码
    virtual-host: /                       #虚拟主机
#--------------------------------------------------------


